name: Actualización del servidor compartido

on:
  push:
    branches:
      - main  # Cambia esto si estás usando una rama diferente

jobs:
  deploy:
    runs-on: ubuntu-latest
    # runs-on: ubuntu-18.04

    steps:
      - name: Checkout del código
        uses: actions/checkout@v2

      - name: Actualizar servidor compartido
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: ./
          remote-dir: ./  # Reemplaza esto con la ruta adecuada en tu servidor
