name: Actualización del servidor compartido

on:
  workflow_run:
    workflows: ["Python Tests"]
    types:
      - completed

jobs:
  check-tests:
    runs-on: ubuntu-latest

    steps:
      # - name: Verificar estado de las pruebas
      #   run: |
      #     if [[ "${{ needs.test.outputs.tests-successful }}" != "true" ]]; then
      #       echo "Las pruebas fallaron, no se ejecutará el despliegue FTP"
      #       exit 1
      #     fi
      - name: Imprimir valor de tests-successful
        run: |
          echo "Valor de tests-successful: ${{ needs.test.outputs.tests-successful }}"

  deploy:
    needs: check-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v2

      - name: Actualizar servidor compartido
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: ./
          # remote-dir: ./  # Reemplaza esto con la ruta adecuada en tu servidor
