name: Python Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      tests-successful: ${{ steps.run-tests.outputs.tests-successful }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        id: run-tests
        run: |
          pytest
          echo "::set-output name=tests-successful::true"
          echo "tests-successful: ${{ steps.run-tests.outputs.tests-successful }}"

